// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: words.sql

package repository

import (
	"context"
)

const getRandomWord = `-- name: GetRandomWord :one
SELECT id, name, created_at FROM word ORDER BY RANDOM() LIMIT 1
`

func (q *Queries) GetRandomWord(ctx context.Context) (Word, error) {
	row := q.db.QueryRowContext(ctx, getRandomWord)
	var i Word
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}
